-- MySQL Script generated by MySQL Workbench
-- Fri Nov 19 11:33:21 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library` DEFAULT CHARACTER SET utf8 ;
USE `library` ;

-- -----------------------------------------------------
-- Table `library`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(20) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(30) NOT NULL,
  `first_name` VARCHAR(30) NOT NULL,
  `patronymic` VARCHAR(30) NOT NULL,
  `birthdate` DATE NOT NULL,
  `gender` VARCHAR(1) NOT NULL,
  `passport` VARCHAR(20) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `registration_date` DATE NOT NULL,
  `rating` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`users_has_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`users_has_roles` (
  `users_id` INT NOT NULL,
  `roles_id` INT NOT NULL,
  INDEX `fk_users_has_roles_roles1_idx` (`roles_id` ASC),
  INDEX `fk_users_has_roles_users_idx` (`users_id` ASC),
  PRIMARY KEY (`users_id`, `roles_id`),
  CONSTRAINT `fk_users_has_roles_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `library`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_roles_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `library`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`publishers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`publishers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `city` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`genres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`authors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(30) NOT NULL,
  `first_name` VARCHAR(30) NOT NULL,
  `patronymic` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `publishers_id` INT NOT NULL,
  `genres_id` INT NOT NULL,
  `types_id` INT NOT NULL,
  `publication_year` INT NOT NULL,
  `pages` INT NOT NULL,
  `part` INT NULL,
  `isbn` VARCHAR(45) NOT NULL,
  `annotation` VARCHAR(300) NULL,
  `price` DECIMAL(7,2) NOT NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_books_genres1_idx` (`genres_id` ASC),
  INDEX `fk_books_types1_idx` (`types_id` ASC),
  INDEX `fk_books_publishers1_idx` (`publishers_id` ASC),
  CONSTRAINT `fk_books_genres1`
    FOREIGN KEY (`genres_id`)
    REFERENCES `library`.`genres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_books_types1`
    FOREIGN KEY (`types_id`)
    REFERENCES `library`.`types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_books_publishers1`
    FOREIGN KEY (`publishers_id`)
    REFERENCES `library`.`publishers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`books_has_authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`books_has_authors` (
  `books_id` INT NOT NULL,
  `authors_id` INT NOT NULL,
  INDEX `fk_books_has_authors_authors1_idx` (`authors_id` ASC),
  INDEX `fk_books_has_authors_books1_idx` (`books_id` ASC),
  PRIMARY KEY (`books_id`, `authors_id`),
  CONSTRAINT `fk_books_has_authors_books1`
    FOREIGN KEY (`books_id`)
    REFERENCES `library`.`books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_books_has_authors_authors1`
    FOREIGN KEY (`authors_id`)
    REFERENCES `library`.`authors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`halls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`halls` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `short_name` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`instances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`instances` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `books_id` INT NOT NULL,
  `number` VARCHAR(10) NOT NULL,
  `halls_id` INT NOT NULL,
  `date_recivied` DATE NOT NULL,
  `date_write_off` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_instances_books1_idx` (`books_id` ASC),
  INDEX `fk_instances_halls1_idx` (`halls_id` ASC),
  CONSTRAINT `fk_instances_books1`
    FOREIGN KEY (`books_id`)
    REFERENCES `library`.`books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_instances_halls1`
    FOREIGN KEY (`halls_id`)
    REFERENCES `library`.`halls` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`books_issuing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`books_issuing` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `instances_id` INT NOT NULL,
  `reader_id` INT NOT NULL,
  `librarian_id` INT NOT NULL,
  `date_issue` DATE NOT NULL,
  `date_return` DATE NULL,
  `date_return_planned` DATE NOT NULL,
  `lost` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_books_issuing_instances1_idx` (`instances_id` ASC),
  INDEX `fk_books_issuing_users1_idx` (`reader_id` ASC),
  INDEX `fk_books_issuing_users2_idx` (`librarian_id` ASC),
  CONSTRAINT `fk_books_issuing_instances1`
    FOREIGN KEY (`instances_id`)
    REFERENCES `library`.`instances` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_books_issuing_users1`
    FOREIGN KEY (`reader_id`)
    REFERENCES `library`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_books_issuing_users2`
    FOREIGN KEY (`librarian_id`)
    REFERENCES `library`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
